In [27]:
import numpy as np 
#Сигмоид 
def nonlin(x,deriv=False):
    if(deriv==True):
        return (x*(1-x))
    return 1/(1+np.exp(-x))

#набор входных данных 
X = np.array([[0,0,1],[0,1,1],[1,0,1],[1,1,1]])

#выходные данные 
y = np.array([0,0,1,1])

#сделаем случайные числа более определенными 
np.random.seed(1)

#инициализируем  веса случайным образом со средним 0 
syn0 = 2*np.random.random((3,1)) - 1

print(syn0)

for iter in range(10000): 
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))
    
    l1_error = y.T - l1
    
    l1_delta = l1_error * nonlin(l1,True)
    
    syn0 += np.dot(l0.T,l1_delta)

print(l1)


[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


ValueError: non-broadcastable output operand with shape (3,1) doesn't match the broadcast shape (3,4)

In [20]:
print(l0.T)

[[0 0 1 1]
 [0 1 0 1]
 [1 1 1 1]]


In [14]:
l1_delta

array([[-0.05289153, -0.05289153,  0.14374119,  0.14374119],
       [-0.08418501, -0.08418501,  0.14725108,  0.14725108],
       [-0.04304896, -0.04304896,  0.13811206,  0.13811206],
       [-0.07172188, -0.07172188,  0.14809799,  0.14809799]])

In [26]:
print(y.T)


[0 0 1 1]
